[package]
name = "simple-router"
version = "0.1.0"
edition = "2021"
description = "A very, very rudementary SSG built in Rust & vanilla JavaScript."
license = "MIT"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.14"
xml = "0.8.20"
